# Generated by Django 3.2.8 on 2022-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.CharField(max_length=30)),
                ('completion_date', models.DateField()),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
