# Generated by Django 3.2.8 on 2022-09-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0002_certificate_course'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_certificates', to='user.learner'),
        ),
    ]
